name: Flutter iOS Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.44.0" # đổi thành version của bạn

      - run: flutter --version

      - run: flutter pub get

      - run: flutter analyze

      - run: flutter test

      - run: flutter build ios --no-codesign
